# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/oasis-tcs/sarif-spec/main/sarif-2.1/schema/sarif-schema-2.1.0.json
#   timestamp: 2026-01-05T03:15:16+00:00

from __future__ import annotations

from typing import Literal, NotRequired, TypeAlias, TypedDict


class PropertyBag(TypedDict):
    tags: NotRequired[list[str]]


DeprecatedGuid: TypeAlias = str


class ReportingConfiguration(TypedDict):
    enabled: NotRequired[bool]
    level: NotRequired[Literal["none", "note", "warning", "error"]]
    rank: NotRequired[float]
    parameters: NotRequired[PropertyBag]
    properties: NotRequired[PropertyBag]


class ToolComponentReference(TypedDict):
    name: NotRequired[str]
    index: NotRequired[int]
    guid: NotRequired[str]
    properties: NotRequired[PropertyBag]


class Address(TypedDict):
    absoluteAddress: NotRequired[int]
    relativeAddress: NotRequired[int]
    length: NotRequired[int]
    kind: NotRequired[str]
    name: NotRequired[str]
    fullyQualifiedName: NotRequired[str]
    offsetFromParent: NotRequired[int]
    index: NotRequired[int]
    parentIndex: NotRequired[int]
    properties: NotRequired[PropertyBag]


class LogicalLocation(TypedDict):
    name: NotRequired[str]
    index: NotRequired[int]
    fullyQualifiedName: NotRequired[str]
    decoratedName: NotRequired[str]
    parentIndex: NotRequired[int]
    kind: NotRequired[str]
    properties: NotRequired[PropertyBag]


class Message1(TypedDict):
    text: str
    markdown: NotRequired[str]
    id: NotRequired[str]
    arguments: NotRequired[list[str]]
    properties: NotRequired[PropertyBag]


class Message2(TypedDict):
    text: NotRequired[str]
    markdown: NotRequired[str]
    id: str
    arguments: NotRequired[list[str]]
    properties: NotRequired[PropertyBag]


Message: TypeAlias = Message1 | Message2


class MultiformatMessageString(TypedDict):
    text: str
    markdown: NotRequired[str]
    properties: NotRequired[PropertyBag]


class Rectangle(TypedDict):
    top: NotRequired[float]
    left: NotRequired[float]
    bottom: NotRequired[float]
    right: NotRequired[float]
    message: NotRequired[Message]
    properties: NotRequired[PropertyBag]


class ReportingDescriptorReference1(TypedDict):
    id: NotRequired[str]
    index: int
    guid: NotRequired[str]
    toolComponent: NotRequired[ToolComponentReference]
    properties: NotRequired[PropertyBag]


class ReportingDescriptorReference2(TypedDict):
    id: NotRequired[str]
    index: NotRequired[int]
    guid: str
    toolComponent: NotRequired[ToolComponentReference]
    properties: NotRequired[PropertyBag]


class ReportingDescriptorReference3(TypedDict):
    id: str
    index: NotRequired[int]
    guid: NotRequired[str]
    toolComponent: NotRequired[ToolComponentReference]
    properties: NotRequired[PropertyBag]


ReportingDescriptorReference: TypeAlias = (
    ReportingDescriptorReference1 | ReportingDescriptorReference2 | ReportingDescriptorReference3
)


class ReportingDescriptorRelationship(TypedDict):
    target: ReportingDescriptorReference
    kinds: NotRequired[list[str]]
    description: NotRequired[Message]
    properties: NotRequired[PropertyBag]


class RunAutomationDetails(TypedDict):
    description: NotRequired[Message]
    id: NotRequired[str]
    guid: NotRequired[str]
    correlationGuid: NotRequired[str]
    properties: NotRequired[PropertyBag]


class TranslationMetadata(TypedDict):
    name: str
    fullName: NotRequired[str]
    shortDescription: NotRequired[MultiformatMessageString]
    fullDescription: NotRequired[MultiformatMessageString]
    downloadUri: NotRequired[str]
    informationUri: NotRequired[str]
    properties: NotRequired[PropertyBag]


class ArtifactContent(TypedDict):
    text: NotRequired[str]
    binary: NotRequired[str]
    rendered: NotRequired[MultiformatMessageString]
    properties: NotRequired[PropertyBag]


class ArtifactLocation(TypedDict):
    uri: NotRequired[str]
    uriBaseId: NotRequired[str]
    index: NotRequired[int]
    description: NotRequired[Message]
    properties: NotRequired[PropertyBag]


class ConfigurationOverride(TypedDict):
    configuration: ReportingConfiguration
    descriptor: ReportingDescriptorReference
    properties: NotRequired[PropertyBag]


class Edge(TypedDict):
    id: str
    label: NotRequired[Message]
    sourceNodeId: str
    targetNodeId: str
    properties: NotRequired[PropertyBag]


class EdgeTraversal(TypedDict):
    edgeId: str
    message: NotRequired[Message]
    finalState: NotRequired[dict[str, MultiformatMessageString]]
    stepOverEdgeCount: NotRequired[int]
    properties: NotRequired[PropertyBag]


class ExternalPropertyFileReference1(TypedDict):
    location: ArtifactLocation
    guid: NotRequired[str]
    itemCount: NotRequired[int]
    properties: NotRequired[PropertyBag]


class ExternalPropertyFileReference2(TypedDict):
    location: NotRequired[ArtifactLocation]
    guid: str
    itemCount: NotRequired[int]
    properties: NotRequired[PropertyBag]


ExternalPropertyFileReference: TypeAlias = (
    ExternalPropertyFileReference1 | ExternalPropertyFileReference2
)


class ExternalPropertyFileReferences(TypedDict):
    conversion: NotRequired[ExternalPropertyFileReference]
    graphs: NotRequired[list[ExternalPropertyFileReference]]
    externalizedProperties: NotRequired[ExternalPropertyFileReference]
    artifacts: NotRequired[list[ExternalPropertyFileReference]]
    invocations: NotRequired[list[ExternalPropertyFileReference]]
    logicalLocations: NotRequired[list[ExternalPropertyFileReference]]
    threadFlowLocations: NotRequired[list[ExternalPropertyFileReference]]
    results: NotRequired[list[ExternalPropertyFileReference]]
    taxonomies: NotRequired[list[ExternalPropertyFileReference]]
    addresses: NotRequired[list[ExternalPropertyFileReference]]
    driver: NotRequired[ExternalPropertyFileReference]
    extensions: NotRequired[list[ExternalPropertyFileReference]]
    policies: NotRequired[list[ExternalPropertyFileReference]]
    translations: NotRequired[list[ExternalPropertyFileReference]]
    webRequests: NotRequired[list[ExternalPropertyFileReference]]
    webResponses: NotRequired[list[ExternalPropertyFileReference]]
    properties: NotRequired[PropertyBag]


class GraphTraversal1(TypedDict):
    runGraphIndex: int
    resultGraphIndex: NotRequired[int]
    description: NotRequired[Message]
    initialState: NotRequired[dict[str, MultiformatMessageString]]
    immutableState: NotRequired[dict[str, MultiformatMessageString]]
    edgeTraversals: NotRequired[list[EdgeTraversal]]
    properties: NotRequired[PropertyBag]


class GraphTraversal2(TypedDict):
    runGraphIndex: NotRequired[int]
    resultGraphIndex: int
    description: NotRequired[Message]
    initialState: NotRequired[dict[str, MultiformatMessageString]]
    immutableState: NotRequired[dict[str, MultiformatMessageString]]
    edgeTraversals: NotRequired[list[EdgeTraversal]]
    properties: NotRequired[PropertyBag]


GraphTraversal: TypeAlias = GraphTraversal1 | GraphTraversal2


class LocationRelationship(TypedDict):
    target: int
    kinds: NotRequired[list[str]]
    description: NotRequired[Message]
    properties: NotRequired[PropertyBag]


class Region1(TypedDict):
    startLine: int
    startColumn: NotRequired[int]
    endLine: NotRequired[int]
    endColumn: NotRequired[int]
    charOffset: NotRequired[int]
    charLength: NotRequired[int]
    byteOffset: NotRequired[int]
    byteLength: NotRequired[int]
    snippet: NotRequired[ArtifactContent]
    message: NotRequired[Message]
    sourceLanguage: NotRequired[str]
    properties: NotRequired[PropertyBag]


class Region2(TypedDict):
    startLine: NotRequired[int]
    startColumn: NotRequired[int]
    endLine: NotRequired[int]
    endColumn: NotRequired[int]
    charOffset: int
    charLength: NotRequired[int]
    byteOffset: NotRequired[int]
    byteLength: NotRequired[int]
    snippet: NotRequired[ArtifactContent]
    message: NotRequired[Message]
    sourceLanguage: NotRequired[str]
    properties: NotRequired[PropertyBag]


class Region3(TypedDict):
    startLine: NotRequired[int]
    startColumn: NotRequired[int]
    endLine: NotRequired[int]
    endColumn: NotRequired[int]
    charOffset: NotRequired[int]
    charLength: NotRequired[int]
    byteOffset: int
    byteLength: NotRequired[int]
    snippet: NotRequired[ArtifactContent]
    message: NotRequired[Message]
    sourceLanguage: NotRequired[str]
    properties: NotRequired[PropertyBag]


Region: TypeAlias = Region1 | Region2 | Region3


class Replacement(TypedDict):
    deletedRegion: Region
    insertedContent: NotRequired[ArtifactContent]
    properties: NotRequired[PropertyBag]


class ReportingDescriptor(TypedDict):
    id: str
    deprecatedIds: NotRequired[list[str]]
    guid: NotRequired[str]
    deprecatedGuids: NotRequired[list[DeprecatedGuid]]
    name: NotRequired[str]
    deprecatedNames: NotRequired[list[str]]
    shortDescription: NotRequired[MultiformatMessageString]
    fullDescription: NotRequired[MultiformatMessageString]
    messageStrings: NotRequired[dict[str, MultiformatMessageString]]
    defaultConfiguration: NotRequired[ReportingConfiguration]
    helpUri: NotRequired[str]
    help: NotRequired[MultiformatMessageString]
    relationships: NotRequired[list[ReportingDescriptorRelationship]]
    properties: NotRequired[PropertyBag]


class SpecialLocations(TypedDict):
    displayBase: NotRequired[ArtifactLocation]
    properties: NotRequired[PropertyBag]


class ToolComponent(TypedDict):
    guid: NotRequired[str]
    name: str
    organization: NotRequired[str]
    product: NotRequired[str]
    productSuite: NotRequired[str]
    shortDescription: NotRequired[MultiformatMessageString]
    fullDescription: NotRequired[MultiformatMessageString]
    fullName: NotRequired[str]
    version: NotRequired[str]
    semanticVersion: NotRequired[str]
    dottedQuadFileVersion: NotRequired[str]
    releaseDateUtc: NotRequired[str]
    downloadUri: NotRequired[str]
    informationUri: NotRequired[str]
    globalMessageStrings: NotRequired[dict[str, MultiformatMessageString]]
    notifications: NotRequired[list[ReportingDescriptor]]
    rules: NotRequired[list[ReportingDescriptor]]
    taxa: NotRequired[list[ReportingDescriptor]]
    locations: NotRequired[list[ArtifactLocation]]
    language: NotRequired[str]
    contents: NotRequired[list[Literal["localizedData", "nonLocalizedData"]]]
    isComprehensive: NotRequired[bool]
    localizedDataSemanticVersion: NotRequired[str]
    minimumRequiredLocalizedDataSemanticVersion: NotRequired[str]
    associatedComponent: NotRequired[ToolComponentReference]
    translationMetadata: NotRequired[TranslationMetadata]
    supportedTaxonomies: NotRequired[list[ToolComponentReference]]
    properties: NotRequired[PropertyBag]


class VersionControlDetails(TypedDict):
    repositoryUri: str
    revisionId: NotRequired[str]
    branch: NotRequired[str]
    revisionTag: NotRequired[str]
    asOfTimeUtc: NotRequired[str]
    mappedTo: NotRequired[ArtifactLocation]
    properties: NotRequired[PropertyBag]


class WebRequest(TypedDict):
    index: NotRequired[int]
    protocol: NotRequired[str]
    version: NotRequired[str]
    target: NotRequired[str]
    method: NotRequired[str]
    headers: NotRequired[dict[str, str]]
    parameters: NotRequired[dict[str, str]]
    body: NotRequired[ArtifactContent]
    properties: NotRequired[PropertyBag]


class WebResponse(TypedDict):
    index: NotRequired[int]
    protocol: NotRequired[str]
    version: NotRequired[str]
    statusCode: NotRequired[int]
    reasonPhrase: NotRequired[str]
    headers: NotRequired[dict[str, str]]
    body: NotRequired[ArtifactContent]
    noResponseReceived: NotRequired[bool]
    properties: NotRequired[PropertyBag]


class Artifact(TypedDict):
    description: NotRequired[Message]
    location: NotRequired[ArtifactLocation]
    parentIndex: NotRequired[int]
    offset: NotRequired[int]
    length: NotRequired[int]
    roles: NotRequired[
        list[
            Literal[
                "analysisTarget",
                "attachment",
                "responseFile",
                "resultFile",
                "standardStream",
                "tracedFile",
                "unmodified",
                "modified",
                "added",
                "deleted",
                "renamed",
                "uncontrolled",
                "driver",
                "extension",
                "translation",
                "taxonomy",
                "policy",
                "referencedOnCommandLine",
                "memoryContents",
                "directory",
                "userSpecifiedConfiguration",
                "toolSpecifiedConfiguration",
                "debugOutputFile",
            ]
        ]
    ]
    mimeType: NotRequired[str]
    contents: NotRequired[ArtifactContent]
    encoding: NotRequired[str]
    sourceLanguage: NotRequired[str]
    hashes: NotRequired[dict[str, str]]
    lastModifiedTimeUtc: NotRequired[str]
    properties: NotRequired[PropertyBag]


class ArtifactChange(TypedDict):
    artifactLocation: ArtifactLocation
    replacements: list[Replacement]
    properties: NotRequired[PropertyBag]


class Attachment(TypedDict):
    description: NotRequired[Message]
    artifactLocation: ArtifactLocation
    regions: NotRequired[list[Region]]
    rectangles: NotRequired[list[Rectangle]]
    properties: NotRequired[PropertyBag]


class Fix(TypedDict):
    description: NotRequired[Message]
    artifactChanges: list[ArtifactChange]
    properties: NotRequired[PropertyBag]


class PhysicalLocation1(TypedDict):
    address: Address
    artifactLocation: NotRequired[ArtifactLocation]
    region: NotRequired[Region]
    contextRegion: NotRequired[Region]
    properties: NotRequired[PropertyBag]


class PhysicalLocation2(TypedDict):
    address: NotRequired[Address]
    artifactLocation: ArtifactLocation
    region: NotRequired[Region]
    contextRegion: NotRequired[Region]
    properties: NotRequired[PropertyBag]


PhysicalLocation: TypeAlias = PhysicalLocation1 | PhysicalLocation2


class ResultProvenance(TypedDict):
    firstDetectionTimeUtc: NotRequired[str]
    lastDetectionTimeUtc: NotRequired[str]
    firstDetectionRunGuid: NotRequired[str]
    lastDetectionRunGuid: NotRequired[str]
    invocationIndex: NotRequired[int]
    conversionSources: NotRequired[list[PhysicalLocation]]
    properties: NotRequired[PropertyBag]


class Tool(TypedDict):
    driver: ToolComponent
    extensions: NotRequired[list[ToolComponent]]
    properties: NotRequired[PropertyBag]


class Location(TypedDict):
    id: NotRequired[int]
    physicalLocation: NotRequired[PhysicalLocation]
    logicalLocations: NotRequired[list[LogicalLocation]]
    message: NotRequired[Message]
    annotations: NotRequired[list[Region]]
    relationships: NotRequired[list[LocationRelationship]]
    properties: NotRequired[PropertyBag]


class Node(TypedDict):
    id: str
    label: NotRequired[Message]
    location: NotRequired[Location]
    children: NotRequired[list[Node]]
    properties: NotRequired[PropertyBag]


class StackFrame(TypedDict):
    location: NotRequired[Location]
    module: NotRequired[str]
    threadId: NotRequired[int]
    parameters: NotRequired[list[str]]
    properties: NotRequired[PropertyBag]


class Suppression(TypedDict):
    guid: NotRequired[str]
    kind: Literal["inSource", "external"]
    status: NotRequired[Literal["accepted", "underReview", "rejected"]]
    justification: NotRequired[str]
    location: NotRequired[Location]
    properties: NotRequired[PropertyBag]


class Graph(TypedDict):
    description: NotRequired[Message]
    nodes: NotRequired[list[Node]]
    edges: NotRequired[list[Edge]]
    properties: NotRequired[PropertyBag]


class Stack(TypedDict):
    message: NotRequired[Message]
    frames: list[StackFrame]
    properties: NotRequired[PropertyBag]


class ThreadFlowLocation(TypedDict):
    index: NotRequired[int]
    location: NotRequired[Location]
    stack: NotRequired[Stack]
    kinds: NotRequired[list[str]]
    taxa: NotRequired[list[ReportingDescriptorReference]]
    module: NotRequired[str]
    state: NotRequired[dict[str, MultiformatMessageString]]
    nestingLevel: NotRequired[int]
    executionOrder: NotRequired[int]
    executionTimeUtc: NotRequired[str]
    importance: NotRequired[Literal["important", "essential", "unimportant"]]
    webRequest: NotRequired[WebRequest]
    webResponse: NotRequired[WebResponse]
    properties: NotRequired[PropertyBag]


class Exception(TypedDict):
    kind: NotRequired[str]
    message: NotRequired[str]
    stack: NotRequired[Stack]
    innerExceptions: NotRequired[list[Exception]]
    properties: NotRequired[PropertyBag]


class Notification(TypedDict):
    locations: NotRequired[list[Location]]
    message: Message
    level: NotRequired[Literal["none", "note", "warning", "error"]]
    threadId: NotRequired[int]
    timeUtc: NotRequired[str]
    exception: NotRequired[Exception]
    descriptor: NotRequired[ReportingDescriptorReference]
    associatedRule: NotRequired[ReportingDescriptorReference]
    properties: NotRequired[PropertyBag]


class ThreadFlow(TypedDict):
    id: NotRequired[str]
    message: NotRequired[Message]
    initialState: NotRequired[dict[str, MultiformatMessageString]]
    immutableState: NotRequired[dict[str, MultiformatMessageString]]
    locations: list[ThreadFlowLocation]
    properties: NotRequired[PropertyBag]


class CodeFlow(TypedDict):
    message: NotRequired[Message]
    threadFlows: list[ThreadFlow]
    properties: NotRequired[PropertyBag]


class Invocation(TypedDict):
    commandLine: NotRequired[str]
    arguments: NotRequired[list[str]]
    responseFiles: NotRequired[list[ArtifactLocation]]
    startTimeUtc: NotRequired[str]
    endTimeUtc: NotRequired[str]
    exitCode: NotRequired[int]
    ruleConfigurationOverrides: NotRequired[list[ConfigurationOverride]]
    notificationConfigurationOverrides: NotRequired[list[ConfigurationOverride]]
    toolExecutionNotifications: NotRequired[list[Notification]]
    toolConfigurationNotifications: NotRequired[list[Notification]]
    exitCodeDescription: NotRequired[str]
    exitSignalName: NotRequired[str]
    exitSignalNumber: NotRequired[int]
    processStartFailureMessage: NotRequired[str]
    executionSuccessful: bool
    machine: NotRequired[str]
    account: NotRequired[str]
    processId: NotRequired[int]
    executableLocation: NotRequired[ArtifactLocation]
    workingDirectory: NotRequired[ArtifactLocation]
    environmentVariables: NotRequired[dict[str, str]]
    stdin: NotRequired[ArtifactLocation]
    stdout: NotRequired[ArtifactLocation]
    stderr: NotRequired[ArtifactLocation]
    stdoutStderr: NotRequired[ArtifactLocation]
    properties: NotRequired[PropertyBag]


class Result(TypedDict):
    ruleId: NotRequired[str]
    ruleIndex: NotRequired[int]
    rule: NotRequired[ReportingDescriptorReference]
    kind: NotRequired[Literal["notApplicable", "pass", "fail", "review", "open", "informational"]]
    level: NotRequired[Literal["none", "note", "warning", "error"]]
    message: Message
    analysisTarget: NotRequired[ArtifactLocation]
    locations: NotRequired[list[Location]]
    guid: NotRequired[str]
    correlationGuid: NotRequired[str]
    occurrenceCount: NotRequired[int]
    partialFingerprints: NotRequired[dict[str, str]]
    fingerprints: NotRequired[dict[str, str]]
    stacks: NotRequired[list[Stack]]
    codeFlows: NotRequired[list[CodeFlow]]
    graphs: NotRequired[list[Graph]]
    graphTraversals: NotRequired[list[GraphTraversal]]
    relatedLocations: NotRequired[list[Location]]
    suppressions: NotRequired[list[Suppression]]
    baselineState: NotRequired[Literal["new", "unchanged", "updated", "absent"]]
    rank: NotRequired[float]
    attachments: NotRequired[list[Attachment]]
    hostedViewerUri: NotRequired[str]
    workItemUris: NotRequired[list[str]]
    provenance: NotRequired[ResultProvenance]
    fixes: NotRequired[list[Fix]]
    taxa: NotRequired[list[ReportingDescriptorReference]]
    webRequest: NotRequired[WebRequest]
    webResponse: NotRequired[WebResponse]
    properties: NotRequired[PropertyBag]


class Conversion(TypedDict):
    tool: Tool
    invocation: NotRequired[Invocation]
    analysisToolLogFiles: NotRequired[list[ArtifactLocation]]
    properties: NotRequired[PropertyBag]


class ExternalProperties(TypedDict):
    schema: NotRequired[str]
    version: NotRequired[Literal["2.1.0"]]
    guid: NotRequired[str]
    runGuid: NotRequired[str]
    conversion: NotRequired[Conversion]
    graphs: NotRequired[list[Graph]]
    externalizedProperties: NotRequired[PropertyBag]
    artifacts: NotRequired[list[Artifact]]
    invocations: NotRequired[list[Invocation]]
    logicalLocations: NotRequired[list[LogicalLocation]]
    threadFlowLocations: NotRequired[list[ThreadFlowLocation]]
    results: NotRequired[list[Result]]
    taxonomies: NotRequired[list[ToolComponent]]
    driver: NotRequired[ToolComponent]
    extensions: NotRequired[list[ToolComponent]]
    policies: NotRequired[list[ToolComponent]]
    translations: NotRequired[list[ToolComponent]]
    addresses: NotRequired[list[Address]]
    webRequests: NotRequired[list[WebRequest]]
    webResponses: NotRequired[list[WebResponse]]
    properties: NotRequired[PropertyBag]


class Run(TypedDict):
    tool: Tool
    invocations: NotRequired[list[Invocation]]
    conversion: NotRequired[Conversion]
    language: NotRequired[str]
    versionControlProvenance: NotRequired[list[VersionControlDetails]]
    originalUriBaseIds: NotRequired[dict[str, ArtifactLocation]]
    artifacts: NotRequired[list[Artifact]]
    logicalLocations: NotRequired[list[LogicalLocation]]
    graphs: NotRequired[list[Graph]]
    results: NotRequired[list[Result]]
    automationDetails: NotRequired[RunAutomationDetails]
    runAggregates: NotRequired[list[RunAutomationDetails]]
    baselineGuid: NotRequired[str]
    redactionTokens: NotRequired[list[str]]
    defaultEncoding: NotRequired[str]
    defaultSourceLanguage: NotRequired[str]
    newlineSequences: NotRequired[list[str]]
    columnKind: NotRequired[Literal["utf16CodeUnits", "unicodeCodePoints"]]
    externalPropertyFileReferences: NotRequired[ExternalPropertyFileReferences]
    threadFlowLocations: NotRequired[list[ThreadFlowLocation]]
    taxonomies: NotRequired[list[ToolComponent]]
    addresses: NotRequired[list[Address]]
    translations: NotRequired[list[ToolComponent]]
    policies: NotRequired[list[ToolComponent]]
    webRequests: NotRequired[list[WebRequest]]
    webResponses: NotRequired[list[WebResponse]]
    specialLocations: NotRequired[SpecialLocations]
    properties: NotRequired[PropertyBag]


StaticAnalysisResultsFormatSarifVersion210JsonSchema = TypedDict(
    "StaticAnalysisResultsFormatSarifVersion210JsonSchema",
    {
        "$schema": NotRequired[str],
        "version": Literal["2.1.0"],
        "runs": list[Run] | None,
        "inlineExternalProperties": NotRequired[list[ExternalProperties]],
        "properties": NotRequired[PropertyBag],
    },
)
